### ISSUE TITLE
请问作者，我有自己的一批图像数据，需要怎么标注和处理才能做成训练集？

### ISSUE THREAD

**Issue by funny000** [Shimmer93/MPCount#11]

**Comment by Shimmer93** [comment]
我没有建过自己的数据集，但应该是要么用开源的工具自己找些人来标注，要么在网络上花钱雇人做标注

**Comment by funny000** [comment]
是那种只标人头坐标的吗，



---原始邮件---
发件人: "PENG ***@***.***&gt;
发送时间: 2024年8月10日(周六) 晚上9:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Shimmer93/MPCount] 请问作者，我有自己的一批图像数据，需要怎么标注和处理才能做成训练集？ (Issue #11)




 
我没有建过自己的数据集，但应该是要么用开源的工具自己找些人来标注，要么在网络上花钱雇人做标注

**Comment by Shimmer93** [comment]
是的

**Comment by funny000** [comment]
好的，谢谢作者
