### ISSUE TITLE
有关b数据集训练，a,qnrf数据集测试出现的问题

### ISSUE THREAD

**Issue by caiyuyu-1** [Shimmer93/MPCount#18]
你好作者，我按照您给的文件进行b数据集的训练，最终对a测试结果为mae: 127.8763 mse: 233.4541，对qnrf测试结果为 mae: 249.3885 mse: 430.5001，和论文值有一定差距，接着我将训练轮次调到了300轮，并在248轮出现最好的结果，其中对a测试结果为 mae: 115.5588 mse:190.4632，对qnrf数据集测试结果为mae: 244.8156 mse: 393.0988 ，虽然有好转，但是结果还是跟论文值有一定差距，想请教一下我该怎么解决这个问题

**Comment by Shimmer93** [comment]
参见 #10
