### ISSUE TITLE
JHU++ dataset download

### ISSUE THREAD

**Issue by RaghadOsamah** [Shimmer93/MPCount#3]
Thank you for sharing your code, but could you please **share the JHU++ dataset** or sample from its annotations 
Thank you in advance

**Comment by Shimmer93** [comment]
Sorry that currently we have no plan to include JHU++ in this repo because of the extra efforts. We will do it after we have spare time for it.

**Comment by RaghadOsamah** [comment]
could you share it with me via email please I need it very soon
alfaresraghad@gmail.com

**Comment by Shimmer93** [comment]
If you only need the dataset itself you can download from its [official website](http://www.crowd-counting.com/).
Below is the splits we used in our experiments:
[jhu_domains.zip](https://github.com/Shimmer93/MPCount/files/15259379/jhu_domains.zip)

**Comment by RaghadOsamah** [comment]
Thank you very much
