### ISSUE TITLE
关于推理部分

### ISSUE THREAD

**Issue by primerL** [Shimmer93/MPCount#4]
想请问一下为什么训练的时候用的是两个模态的数据，但是推理和验证只用了一个模态

**Comment by Shimmer93** [comment]
您说的模态是指领域吗？
训练时我们通过用各种图像增强构建新的领域，来让模型学习领域不变的特征。推理和验证不需要学习特征，只需要在当前领域预测准确，所以没有这一步。

**Comment by primerL** [comment]
好的，感谢您的回复，我理解了
