### ISSUE TITLE
关于多卡训练与自定义数据集

### ISSUE THREAD

**Issue by Chenguoz** [Shimmer93/MPCount#5]
您好！非常不错的工作！
请问一下代码可能支持多卡训练吗？
另外如果将该模型在规模大约3000张图像的自定义数据集上训练的话，您更推荐使用哪个config文件呢？```sta_train.yml```或是```stb_train.yml```呢，或者说config文件中的哪些超参需要按数据规模调整呢。

**Comment by Shimmer93** [comment]
感谢支持！
实验用的数据集都比较小所以没有考虑多卡训练，也暂时没有加入的打算，不好意思
自定义数据集的 config 主要是需要把 `steps_per_epoch` 改成 number of images / batch size，其他参数的话应该没有太多要改的，可能 `num_epoches` 和 `scheduler` 下的 `epochs` 可以根据需要训练情况适当修改，前者是实际训练的 epoch 数后者是 scheduler 规划的完整 epoch 数。`sta_train.yml` 和 `stb_train.yml` 没有本质区别。

**Comment by Chenguoz** [comment]
感谢您如此及时的回复:)
