### ISSUE TITLE
Hi author, which use  shanghaiTeachA or shanghaiTeachB dataset in your great work?

### ISSUE THREAD

**Issue by funny000** [Shimmer93/MPCount#6]
thanks author opensource the great work.
I find two version shanghaiTeachA and B dataset, and there is very different, so can you share a pair of shanghaiTeach dataset with BaiDuDriver or OneDriver?

**Comment by Shimmer93** [comment]
Thanks for your interest! You can download it from [Kaggle](https://www.kaggle.com/datasets/tthien/shanghaitech).

**Comment by funny000** [comment]
thanks author reply, i will download it.
