### ISSUE TITLE
结果指标问题

### ISSUE THREAD

**Issue by D-VVY** [Shimmer93/MPCount#9]
作者您好，非常感谢您的工作。我使用sta_train.yml文件对训练上海科技A数据集进行多次训练，但还是均与论文里面的指标存在着差距，请问您是否有什么建议？

**Comment by Shimmer93** [comment]
你好，实在不好意思，我在代码中加入了控制 seed 的代码但不知为何训练还是有随机性。你可以试着改变一下 seed 和 epoch 重新训练。

本来想找一找论文指标对应的 log 文件，但 cluster 出错导致数据丢失了，挺头疼的。

**Comment by D-VVY** [comment]
好的，多谢回复
